name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true #remove labels when matching files are reverted